version: '3.4'

services:
  app_db:
      image: postgres
      env_file:
        - ./.env
      deploy:
        resources:
          limits:
            memory: 512M
          reservations:
            memory: 128M
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5432:5432'
      networks:
        - default
      volumes:
        # Copy DB schema to container for creation
        - ./db_schema/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  minitest:
    image: minitest
    env_file:
        - ./.env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - app_db
